services:
  ipshow:
    build: .
    container_name: ipshow
    volumes:
      - ./data:/root/data
    restart: always

  caddy:
    image: caddy:latest
    container_name: ipshow-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always

volumes:
  caddy_data:
  caddy_config:
